version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - "DATABASE_HOST=127.0.0.1"
      - "POSTGRES_USER=pizza_admin"
      - "POSTGRES_PASSWORD=pizza"
      - "POSTGRES_DB=pizza_order_management_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
